### ISSUE TITLE
ConfigBuilder repo

### ISSUE THREAD

**Issue by twiernik** [Sitecore/Sitecore-Config-Builder#13]
Link in readme.md doesn't work https://github.com/Sitecore/Sitecore.Diagnostics.ConfigBuilder
Is this code base still available?

**Comment by AlenPelin** [comment]
No, it contained significant part of Sitecore.Kernel code extract which is not allowed to be public.

**Comment by AlenPelin** [comment]
However there is publicly available `Sitecore.Diagnostics.ConfigBuilder` NuGet package.
