### ISSUE TITLE
Tool doesn't resolve version for the hotfixes

### ISSUE THREAD

**Issue by Zvirja** [Sitecore/Sitecore-Config-Builder#3]
It appears that tool doesn't work property for hotfixes. Consider the following `sitecore.version.xml` file content:
```xml
<?xml version="1.0" encoding="utf-8"?>
<information>
  <version>
    <major>6</major>
    <minor>6</minor>
    <build>0</build>
    <revision>130529 (FIX #400290) (FIX #400292)</revision>
  </version>
  <date>May 29, 2013</date>
  <title>Sitecore.NET</title>
  <company>Sitecore Corporation</company>
  <copyright>© Sitecore. All rights reserved.</copyright>
</information>
```

Tool will not recognize the version. However, if I remove the hotfix appending, it will do.
Please fix tool to support patched revision.

**Comment by AlenPelin** [comment]
Indeed, it was never meant to support hotfixes as SIS doesn't support that. Do you think that tool should treat hotfix as non-hotfix?
