### ISSUE TITLE
Show update number in versions picker

### ISSUE THREAD

**Issue by Zvirja** [Sitecore/Sitecore-Config-Builder#4]
Currently the version picker doesn't show the update number, so it might be pretty hard to find the exact edition I need i this long and exhausting list:

![image](https://cloud.githubusercontent.com/assets/1074182/11657214/accf4e6a-9dc3-11e5-94a5-bd2c142bd86b.png)

Could you please display update number as well? Example: ``8.0 rev. 150812 (Update 5)``

**Comment by EugeneTkachenko** [comment]
I've added ([developed](https://github.com/Sitecore/Sitecore-Config-Builder/commit/b9f0963bba9876f47290d3a3a7c78258ca5daffe)) update label (number) into versions picker.

**Comment by AlenPelin** [comment]
Verified.
